## 1.01 Get Player Statistics
Individual player statistics acquired from [basketball-reference.com](basketball-reference.com) using the `basketball_reference_web_scraper` library. I researched and learned how to use this library from the documentation here: https://pypi.org/project/basketball-reference-web-scraper/

In [1]:
import pandas as pd
import numpy as np

In [2]:
from basketball_reference_web_scraper import client

In [3]:
# initialize dictionary in which to append a dataframe of each year's player's statistics
dfs = {}
for i in range(1979,2020):
    dfs[i]=pd.DataFrame(client.players_season_totals(season_end_year=i))

In [5]:
# add season column for each dataframe
for i in range(1979,2020):
    dfs[i]['season']=i-1

In [7]:
for i in range(1979,2020):
    dfs[i]['team'] = dfs[i]['team'].astype(str)

In [10]:
dfs[2019]

,slug,name,positions,age,team,games_played,games_started,minutes_played,made_field_goals,attempted_field_goals,...,attempted_free_throws,offensive_rebounds,defensive_rebounds,assists,steals,blocks,turnovers,personal_fouls,points,season
0,abrinal01,Álex Abrines,[Position.SHOOTING_GUARD],25,Team.OKLAHOMA_CITY_THUNDER,31,2,588,56,157,...,13,5,43,20,17,6,14,53,165,2018
1,acyqu01,Quincy Acy,[Position.POWER_FORWARD],28,Team.PHOENIX_SUNS,10,0,123,4,18,...,10,3,22,8,1,4,4,24,17,2018
2,adamsja01,Jaylen Adams,[Position.POINT_GUARD],22,Team.ATLANTA_HAWKS,34,1,428,38,110,...,9,11,49,65,14,5,28,45,108,2018
3,adamsst01,Steven Adams,[Position.CENTER],25,Team.OKLAHOMA_CITY_THUNDER,80,80,2669,481,809,...,292,391,369,124,117,76,135,204,1108,2018
4,adebaba01,Bam Adebayo,[Position.CENTER],21,Team.MIAMI_HEAT,82,28,1913,280,486,...,226,165,432,184,71,65,121,203,729,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
617,zellety01,Tyler Zeller,[Position.CENTER],29,Team.ATLANTA_HAWKS,2,0,11,0,2,...,0,2,4,1,0,0,0,4,0,2018
618,zellety01,Tyler Zeller,[Position.CENTER],29,Team.MEMPHIS_GRIZZLIES,4,1,82,16,28,...,18,9,9,3,1,3,4,16,46,2018
619,zizican01,Ante Žižić,[Position.CENTER],22,Team.CLEVELAND_CAVALIERS,59,25,1082,183,331,...,132,108,212,53,13,22,61,113,459,2018
620,zubaciv01,Ivica Zubac,[Position.CENTER],21,Team.LOS_ANGELES_LAKERS,33,12,516,112,193,...,66,54,108,25,4,27,33,73,281,2018
621,zubaciv01,Ivica Zubac,[Position.CENTER],21,Team.LOS_ANGELES_CLIPPERS,26,25,524,100,186,...,60,61,139,38,10,24,37,64,244,2018

In [11]:
teams = {}
for i in range(1979,2020):
    teams[i]=pd.DataFrame(dfs[i].groupby(['team']).sum())
    teams[i]['season']=i-1

In [12]:
teams[1980]

,age,games_played,games_started,minutes_played,made_field_goals,attempted_field_goals,made_three_point_field_goals,attempted_three_point_field_goals,made_free_throws,attempted_free_throws,offensive_rebounds,defensive_rebounds,assists,steals,blocks,turnovers,personal_fouls,points,season
team,,,,,,,,,,,,,,,,,,,
None,1219,2394,0,59440,10680,22779,275,895,4818,6465,3815,7460,6012,2057,1087,4191,5924,26453,1979
Team.ATLANTA_HAWKS,392,858,0,19780,3261,7027,13,75,2038,2645,1369,2406,1913,782,539,1466,2293,8573,1979
Team.BOSTON_CELTICS,331,828,410,19880,3617,7387,162,422,1907,2449,1227,2457,2198,809,308,1490,1974,9303,1979
Team.CHICAGO_BULLS,398,800,0,19905,3362,6943,70,275,2019,2592,1115,2465,2152,704,392,1661,2146,8813,1979
Team.CLEVELAND_CAVALIERS,414,796,0,19930,3811,8041,36,187,1702,2205,1307,2381,2108,764,342,1349,1934,9360,1979
Team.DENVER_NUGGETS,391,795,0,19830,3462,7470,83,255,1871,2539,1311,2524,2079,746,404,1497,1917,8878,1979
Team.DETROIT_PISTONS,420,770,0,19780,3643,7596,57,219,1590,2149,1226,2415,1950,783,562,1727,2069,8933,1979
Team.GOLDEN_STATE_WARRIORS,365,825,0,19880,3527,7318,27,121,1412,1914,1155,2437,2028,779,339,1455,2082,8493,1979
Team.HOUSTON_ROCKETS,406,774,0,19930,3599,7496,104,379,1782,2326,1394,2217,2149,782,373,1535,1927,9084,1979
Team.INDIANA_PACERS,405,795,0,19855,3639,7689,88,314,1753,2333,1398,2326,2148,900,530,1500,1973,9119,1979
Team.LOS_ANGELES_LAKERS,384,757,0,19880,3898,7368,20,100,1622,2092,1085,2653,2413,774,546,1626,1784,9438,1979
Team.MILWAUKEE_BUCKS,306,837,0,19805,3685,7553,50,155,1605,2102,1245,2396,2277,778,510,1463,1937,9025,1979
Team.NEW_JERSEY_NETS,423,789,0,19805,3456,7504,85,298,1882,2406,1229,2535,2094,869,581,1691,2181,8879,1979
Team.NEW_YORK_KNICKS,327,845,0,19780,3802,7672,42,191,1698,2274,1236,2303,2265,881,457,1589,2168,9344,1979
Team.PHILADELPHIA_76ERS,367,747,0,19855,3523,7156,27,125,1876,2431,1187,2635,2226,792,652,1674,1860,8949,1979
Team.PHOENIX_SUNS,310,863,0,19755,3570,7235,68,280,1906,2466,1071,2458,2283,908,344,1615,1853,9114,1979
Team.PORTLAND_TRAIL_BLAZERS,393,801,0,19780,3408,7167,26,132,1560,2100,1295,2408,1898,708,472,1523,1956,8402,1979
Team.SAN_ANTONIO_SPURS,396,796,0,19755,3856,7738,52,206,2024,2528,1153,2515,2326,771,333,1574,2103,9788,1979
Team.SEATTLE_SUPERSONICS,292,821,0,19830,3554,7565,59,189,1730,2253,1380,2550,2043,750,428,1482,1865,8897,1979
Team.UTAH_JAZZ,513,806,0,19805,3382,6817,59,185,1571,1943,967,2359,2005,656,362,1488,2006,8394,1979

In [13]:
allyears = teams[1979]
for i in range(1980,2020):
    allyears = pd.concat([allyears,teams[i]])

In [14]:
allyears

,age,games_played,games_started,minutes_played,made_field_goals,attempted_field_goals,made_three_point_field_goals,attempted_three_point_field_goals,made_free_throws,attempted_free_throws,offensive_rebounds,defensive_rebounds,assists,steals,blocks,turnovers,personal_fouls,points,season
team,,,,,,,,,,,,,,,,,,,
None,1462,3183,0,79070,14821,30734,0,0,7215,9700,5126,10261,8026,2902,1742,6353,8290,36857,1978
Team.ATLANTA_HAWKS,316,844,0,19855,3505,7410,0,0,1940,2534,1381,2341,1938,801,596,1497,2424,8950,1978
Team.BOSTON_CELTICS,484,781,0,19680,3527,7347,0,0,1820,2321,1119,2396,1995,710,283,1690,1977,8874,1978
Team.CHICAGO_BULLS,360,828,0,19780,3478,7108,0,0,1632,2184,1224,2544,2169,576,324,1784,1970,8588,1978
Team.CLEVELAND_CAVALIERS,376,796,0,19680,3556,7602,0,0,1620,2103,1229,2256,1796,688,334,1347,2027,8732,1978
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Team.SACRAMENTO_KINGS,496,878,410,19732,3541,7637,927,2455,1354,1865,906,2819,2083,679,363,1058,1751,9363,2018
Team.SAN_ANTONIO_SPURS,443,906,410,19805,3468,7248,812,2071,1408,1720,757,2910,2013,501,386,969,1487,9156,2018
Team.TORONTO_RAPTORS,596,892,410,19878,3460,7305,1015,2771,1449,1803,786,2920,2085,680,437,1093,1724,9384,2018
Team.UTAH_JAZZ,483,922,410,19755,3314,7082,993,2789,1540,2092,820,2981,2133,663,483,1210,1728,9161,2018
Team.WASHINGTON_WIZARDS,665,826,410,19932,3456,7387,930,2731,1508,1963,794,2679,2154,683,379,1120,1701,9350,2018

In [15]:
allyears.to_csv('allyears_teams.csv')

In [16]:
# create master dataset containing each individual season's dataset
allyears_players = dfs[1979]
for i in range(1980,2020):
    allyears_players = pd.concat([allyears_players,dfs[i]])

In [17]:
allyears_players

,slug,name,positions,age,team,games_played,games_started,minutes_played,made_field_goals,attempted_field_goals,...,attempted_free_throws,offensive_rebounds,defensive_rebounds,assists,steals,blocks,turnovers,personal_fouls,points,season
0,abdulka01,Kareem Abdul-Jabbar*,[Position.CENTER],31,Team.LOS_ANGELES_LAKERS,80,0,3157,777,1347,...,474,207,818,431,76,316,282,230,1903,1978
1,abernto01,Tom Abernethy,[Position.POWER_FORWARD],24,Team.GOLDEN_STATE_WARRIORS,70,0,1219,176,342,...,94,74,142,79,39,13,32,133,422,1978
2,adamsal01,Alvan Adams,[Position.CENTER],24,Team.PHOENIX_SUNS,77,0,2364,569,1073,...,289,220,485,360,110,63,279,246,1369,1978
3,allenlu01,Lucius Allen,[Position.POINT_GUARD],31,None,31,0,413,69,174,...,33,14,32,44,21,6,30,52,157,1978
4,anderki01,Kim Anderson,[Position.SMALL_FORWARD],23,Team.PORTLAND_TRAIL_BLAZERS,21,0,224,24,77,...,28,17,28,15,4,5,22,42,63,1978
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
617,zellety01,Tyler Zeller,[Position.CENTER],29,Team.ATLANTA_HAWKS,2,0,11,0,2,...,0,2,4,1,0,0,0,4,0,2018
618,zellety01,Tyler Zeller,[Position.CENTER],29,Team.MEMPHIS_GRIZZLIES,4,1,82,16,28,...,18,9,9,3,1,3,4,16,46,2018
619,zizican01,Ante Žižić,[Position.CENTER],22,Team.CLEVELAND_CAVALIERS,59,25,1082,183,331,...,132,108,212,53,13,22,61,113,459,2018
620,zubaciv01,Ivica Zubac,[Position.CENTER],21,Team.LOS_ANGELES_LAKERS,33,12,516,112,193,...,66,54,108,25,4,27,33,73,281,2018
621,zubaciv01,Ivica Zubac,[Position.CENTER],21,Team.LOS_ANGELES_CLIPPERS,26,25,524,100,186,...,60,61,139,38,10,24,37,64,244,2018

In [18]:
allyears_players.to_csv('allyears_players.csv')