## 1.03 Combing Player

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [7]:
stats = pd.read_csv('allyears_players.csv')
salary = pd.read_csv('player_salary_data.csv')

In [8]:
pd.set_option('display.max_columns', None)

In [9]:
stats.head()

,Unnamed: 0,slug,name,positions,age,team,games_played,games_started,minutes_played,made_field_goals,attempted_field_goals,made_three_point_field_goals,attempted_three_point_field_goals,made_free_throws,attempted_free_throws,offensive_rebounds,defensive_rebounds,assists,steals,blocks,turnovers,personal_fouls,points,season
0,0,abdulka01,Kareem Abdul-Jabbar*,[<Position.CENTER: 'CENTER'>],31,Team.LOS_ANGELES_LAKERS,80,0,3157,777,1347,0,0,349,474,207,818,431,76,316,282,230,1903,1978
1,1,abernto01,Tom Abernethy,[<Position.POWER_FORWARD: 'POWER FORWARD'>],24,Team.GOLDEN_STATE_WARRIORS,70,0,1219,176,342,0,0,70,94,74,142,79,39,13,32,133,422,1978
2,2,adamsal01,Alvan Adams,[<Position.CENTER: 'CENTER'>],24,Team.PHOENIX_SUNS,77,0,2364,569,1073,0,0,231,289,220,485,360,110,63,279,246,1369,1978
3,3,allenlu01,Lucius Allen,[<Position.POINT_GUARD: 'POINT GUARD'>],31,None,31,0,413,69,174,0,0,19,33,14,32,44,21,6,30,52,157,1978
4,4,anderki01,Kim Anderson,[<Position.SMALL_FORWARD: 'SMALL FORWARD'>],23,Team.PORTLAND_TRAIL_BLAZERS,21,0,224,24,77,0,0,15,28,17,28,15,4,5,22,42,63,1978

In [10]:
salary.head()

   Unnamed: 0            Player      Salary  Year
0           0     Patrick Ewing  $4,250,000  1990
1           1  Hot Rod Williams  $3,785,000  1990
2           2   Hakeem Olajuwon  $3,175,000  1990
3           3   Charles Barkley  $2,900,000  1990
4           4      Chris Mullin  $2,850,000  1990

In [25]:
salary.drop(['Unnamed: 0'], axis=1, inplace=True)

In [26]:
salary.dtypes

Player    object
Salary    object
Year       int64
dtype: object

In [27]:
salary['name_season']=salary['Player']+salary['Year'].astype(str)

In [28]:
salary

                 Player      Salary  Year           name_season
0         Patrick Ewing  $4,250,000  1990     Patrick Ewing1990
1      Hot Rod Williams  $3,785,000  1990  Hot Rod Williams1990
2       Hakeem Olajuwon  $3,175,000  1990   Hakeem Olajuwon1990
3       Charles Barkley  $2,900,000  1990   Charles Barkley1990
4          Chris Mullin  $2,850,000  1990      Chris Mullin1990
...                 ...         ...   ...                   ...
13453   Michael Frazier     $47,370  2018   Michael Frazier2018
13454    Tahjere McCall     $47,370  2018    Tahjere McCall2018
13455    Mitchell Creek     $47,370  2018    Mitchell Creek2018
13456   Isaac Humphries     $47,370  2018   Isaac Humphries2018
13457     Jordan Sibert     $47,370  2018     Jordan Sibert2018

[13458 rows x 4 columns]

In [11]:
stats['name'] = stats['name'].map(lambda x: x.rstrip('*'))

In [12]:
stats.head()

,Unnamed: 0,slug,name,positions,age,team,games_played,games_started,minutes_played,made_field_goals,attempted_field_goals,made_three_point_field_goals,attempted_three_point_field_goals,made_free_throws,attempted_free_throws,offensive_rebounds,defensive_rebounds,assists,steals,blocks,turnovers,personal_fouls,points,season
0,0,abdulka01,Kareem Abdul-Jabbar,[<Position.CENTER: 'CENTER'>],31,Team.LOS_ANGELES_LAKERS,80,0,3157,777,1347,0,0,349,474,207,818,431,76,316,282,230,1903,1978
1,1,abernto01,Tom Abernethy,[<Position.POWER_FORWARD: 'POWER FORWARD'>],24,Team.GOLDEN_STATE_WARRIORS,70,0,1219,176,342,0,0,70,94,74,142,79,39,13,32,133,422,1978
2,2,adamsal01,Alvan Adams,[<Position.CENTER: 'CENTER'>],24,Team.PHOENIX_SUNS,77,0,2364,569,1073,0,0,231,289,220,485,360,110,63,279,246,1369,1978
3,3,allenlu01,Lucius Allen,[<Position.POINT_GUARD: 'POINT GUARD'>],31,None,31,0,413,69,174,0,0,19,33,14,32,44,21,6,30,52,157,1978
4,4,anderki01,Kim Anderson,[<Position.SMALL_FORWARD: 'SMALL FORWARD'>],23,Team.PORTLAND_TRAIL_BLAZERS,21,0,224,24,77,0,0,15,28,17,28,15,4,5,22,42,63,1978

In [13]:
stats['made_two_point_field_goals']=stats['made_field_goals']-stats['made_three_point_field_goals']
stats['attempted_two_point_field_goals']=stats['attempted_field_goals']-stats['attempted_three_point_field_goals']
stats['fg_pct']=stats['made_field_goals']/stats['attempted_field_goals']
stats['2fg_pct']=stats['made_two_point_field_goals']/stats['attempted_two_point_field_goals']
stats['3fg_pct']=stats['made_three_point_field_goals']/stats['attempted_three_point_field_goals']

In [32]:
stats['ft_pct']=stats['made_free_throws']/stats['attempted_free_throws']

In [21]:
stats['name_season']=stats['name']+stats['season'].astype(str)

In [23]:
stats.drop(['Unnamed: 0', 'season1'], axis=1, inplace=True)

In [24]:
stats

,slug,name,positions,age,team,games_played,games_started,minutes_played,made_field_goals,attempted_field_goals,made_three_point_field_goals,attempted_three_point_field_goals,made_free_throws,attempted_free_throws,offensive_rebounds,defensive_rebounds,assists,steals,blocks,turnovers,personal_fouls,points,season,made_two_point_field_goals,attempted_two_point_field_goals,fg_pct,2fg_pct,3fg_pct,name_season
0,abdulka01,Kareem Abdul-Jabbar,[<Position.CENTER: 'CENTER'>],31,Team.LOS_ANGELES_LAKERS,80,0,3157,777,1347,0,0,349,474,207,818,431,76,316,282,230,1903,1978,777,1347,0.576837,0.576837,NaN,Kareem Abdul-Jabbar1978
1,abernto01,Tom Abernethy,[<Position.POWER_FORWARD: 'POWER FORWARD'>],24,Team.GOLDEN_STATE_WARRIORS,70,0,1219,176,342,0,0,70,94,74,142,79,39,13,32,133,422,1978,176,342,0.514620,0.514620,NaN,Tom Abernethy1978
2,adamsal01,Alvan Adams,[<Position.CENTER: 'CENTER'>],24,Team.PHOENIX_SUNS,77,0,2364,569,1073,0,0,231,289,220,485,360,110,63,279,246,1369,1978,569,1073,0.530289,0.530289,NaN,Alvan Adams1978
3,allenlu01,Lucius Allen,[<Position.POINT_GUARD: 'POINT GUARD'>],31,None,31,0,413,69,174,0,0,19,33,14,32,44,21,6,30,52,157,1978,69,174,0.396552,0.396552,NaN,Lucius Allen1978
4,anderki01,Kim Anderson,[<Position.SMALL_FORWARD: 'SMALL FORWARD'>],23,Team.PORTLAND_TRAIL_BLAZERS,21,0,224,24,77,0,0,15,28,17,28,15,4,5,22,42,63,1978,24,77,0.311688,0.311688,NaN,Kim Anderson1978
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18826,zellety01,Tyler Zeller,[<Position.CENTER: 'CENTER'>],29,Team.ATLANTA_HAWKS,2,0,11,0,2,0,1,0,0,2,4,1,0,0,0,4,0,2018,0,1,0.000000,0.000000,0.0,Tyler Zeller2018
18827,zellety01,Tyler Zeller,[<Position.CENTER: 'CENTER'>],29,Team.MEMPHIS_GRIZZLIES,4,1,82,16,28,0,0,14,18,9,9,3,1,3,4,16,46,2018,16,28,0.571429,0.571429,NaN,Tyler Zeller2018
18828,zizican01,Ante Žižić,[<Position.CENTER: 'CENTER'>],22,Team.CLEVELAND_CAVALIERS,59,25,1082,183,331,0,0,93,132,108,212,53,13,22,61,113,459,2018,183,331,0.552870,0.552870,NaN,Ante Žižić2018
18829,zubaciv01,Ivica Zubac,[<Position.CENTER: 'CENTER'>],21,Team.LOS_ANGELES_LAKERS,33,12,516,112,193,0,0,57,66,54,108,25,4,27,33,73,281,2018,112,193,0.580311,0.580311,NaN,Ivica Zubac2018
18830,zubaciv01,Ivica Zubac,[<Position.CENTER: 'CENTER'>],21,Team.LOS_ANGELES_CLIPPERS,26,25,524,100,186,0,0,44,60,61,139,38,10,24,37,64,244,2018,100,186,0.537634,0.537634,NaN,Ivica Zubac2018

In [34]:
stats.columns

Index(['slug', 'name', 'positions', 'age', 'team', 'games_played',
       'games_started', 'minutes_played', 'made_field_goals',
       'attempted_field_goals', 'made_three_point_field_goals',
       'attempted_three_point_field_goals', 'made_free_throws',
       'attempted_free_throws', 'offensive_rebounds', 'defensive_rebounds',
       'assists', 'steals', 'blocks', 'turnovers', 'personal_fouls', 'points',
       'season', 'made_two_point_field_goals',
       'attempted_two_point_field_goals', 'fg_pct', '2fg_pct', '3fg_pct',
       'name_season', 'ft_pct'],
      dtype='object')

In [35]:
features = ['name', 'positions', 'age', 'team', 'games_played',
       'games_started', 'minutes_played', 'made_field_goals',
       'attempted_field_goals', 'made_three_point_field_goals',
       'attempted_three_point_field_goals', 'made_free_throws',
       'attempted_free_throws', 'offensive_rebounds', 'defensive_rebounds',
       'assists', 'steals', 'blocks', 'turnovers', 'personal_fouls', 'points',
       'season', 'made_two_point_field_goals',
       'attempted_two_point_field_goals', 'fg_pct', '2fg_pct', '3fg_pct',
       'name_season', 'ft_pct']

In [36]:
stats1=stats.merge(salary, on='name_season', how='left')

In [37]:
stats1

,slug,name,positions,age,team,games_played,games_started,minutes_played,made_field_goals,attempted_field_goals,made_three_point_field_goals,attempted_three_point_field_goals,made_free_throws,attempted_free_throws,offensive_rebounds,defensive_rebounds,assists,steals,blocks,turnovers,personal_fouls,points,season,made_two_point_field_goals,attempted_two_point_field_goals,fg_pct,2fg_pct,3fg_pct,name_season,ft_pct,Player,Salary,Year
0,abdulka01,Kareem Abdul-Jabbar,[<Position.CENTER: 'CENTER'>],31,Team.LOS_ANGELES_LAKERS,80,0,3157,777,1347,0,0,349,474,207,818,431,76,316,282,230,1903,1978,777,1347,0.576837,0.576837,NaN,Kareem Abdul-Jabbar1978,0.736287,NaN,NaN,NaN
1,abernto01,Tom Abernethy,[<Position.POWER_FORWARD: 'POWER FORWARD'>],24,Team.GOLDEN_STATE_WARRIORS,70,0,1219,176,342,0,0,70,94,74,142,79,39,13,32,133,422,1978,176,342,0.514620,0.514620,NaN,Tom Abernethy1978,0.744681,NaN,NaN,NaN
2,adamsal01,Alvan Adams,[<Position.CENTER: 'CENTER'>],24,Team.PHOENIX_SUNS,77,0,2364,569,1073,0,0,231,289,220,485,360,110,63,279,246,1369,1978,569,1073,0.530289,0.530289,NaN,Alvan Adams1978,0.799308,NaN,NaN,NaN
3,allenlu01,Lucius Allen,[<Position.POINT_GUARD: 'POINT GUARD'>],31,None,31,0,413,69,174,0,0,19,33,14,32,44,21,6,30,52,157,1978,69,174,0.396552,0.396552,NaN,Lucius Allen1978,0.575758,NaN,NaN,NaN
4,anderki01,Kim Anderson,[<Position.SMALL_FORWARD: 'SMALL FORWARD'>],23,Team.PORTLAND_TRAIL_BLAZERS,21,0,224,24,77,0,0,15,28,17,28,15,4,5,22,42,63,1978,24,77,0.311688,0.311688,NaN,Kim Anderson1978,0.535714,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18828,zellety01,Tyler Zeller,[<Position.CENTER: 'CENTER'>],29,Team.ATLANTA_HAWKS,2,0,11,0,2,0,1,0,0,2,4,1,0,0,0,4,0,2018,0,1,0.000000,0.000000,0.0,Tyler Zeller2018,NaN,Tyler Zeller,"$213,948",2018.0
18829,zellety01,Tyler Zeller,[<Position.CENTER: 'CENTER'>],29,Team.MEMPHIS_GRIZZLIES,4,1,82,16,28,0,0,14,18,9,9,3,1,3,4,16,46,2018,16,28,0.571429,0.571429,NaN,Tyler Zeller2018,0.777778,Tyler Zeller,"$213,948",2018.0
18830,zizican01,Ante Žižić,[<Position.CENTER: 'CENTER'>],22,Team.CLEVELAND_CAVALIERS,59,25,1082,183,331,0,0,93,132,108,212,53,13,22,61,113,459,2018,183,331,0.552870,0.552870,NaN,Ante Žižić2018,0.704545,NaN,NaN,NaN
18831,zubaciv01,Ivica Zubac,[<Position.CENTER: 'CENTER'>],21,Team.LOS_ANGELES_LAKERS,33,12,516,112,193,0,0,57,66,54,108,25,4,27,33,73,281,2018,112,193,0.580311,0.580311,NaN,Ivica Zubac2018,0.863636,Ivica Zubac,"$1,544,951",2018.0
18832,zubaciv01,Ivica Zubac,[<Position.CENTER: 'CENTER'>],21,Team.LOS_ANGELES_CLIPPERS,26,25,524,100,186,0,0,44,60,61,139,38,10,24,37,64,244,2018,100,186,0.537634,0.537634,NaN,Ivica Zubac2018,0.733333,Ivica Zubac,"$1,544,951",2018.0

In [38]:
stats1.drop(['slug', 'Player','Year'], axis=1, inplace=True)

In [39]:
stats1 = stats1.dropna(axis=0, subset=['Salary'])

In [40]:
stats1

,name,positions,age,team,games_played,games_started,minutes_played,made_field_goals,attempted_field_goals,made_three_point_field_goals,attempted_three_point_field_goals,made_free_throws,attempted_free_throws,offensive_rebounds,defensive_rebounds,assists,steals,blocks,turnovers,personal_fouls,points,season,made_two_point_field_goals,attempted_two_point_field_goals,fg_pct,2fg_pct,3fg_pct,name_season,ft_pct,Salary
4248,Alaa Abdelnaby,[<Position.POWER_FORWARD: 'POWER FORWARD'>],22,Team.PORTLAND_TRAIL_BLAZERS,43,0,290,55,116,0,0,25,44,27,62,12,4,12,22,39,135,1990,55,116,0.474138,0.474138,NaN,Alaa Abdelnaby1990,0.568182,"$395,000"
4249,Mahmoud Abdul-Rauf,[<Position.POINT_GUARD: 'POINT GUARD'>],21,Team.DENVER_NUGGETS,67,19,1505,417,1009,24,100,84,98,34,87,206,55,4,110,149,942,1990,393,909,0.413280,0.432343,0.240000,Mahmoud Abdul-Rauf1990,0.857143,"$1,660,000"
4250,Mark Acres,[<Position.CENTER: 'CENTER'>],28,Team.ORLANDO_MAGIC,68,0,1313,109,214,1,3,66,101,140,219,25,25,25,42,218,285,1990,108,211,0.509346,0.511848,0.333333,Mark Acres1990,0.653465,"$437,000"
4251,Michael Adams,[<Position.POINT_GUARD: 'POINT GUARD'>],28,Team.DENVER_NUGGETS,66,66,2346,560,1421,167,564,465,529,58,198,693,147,6,240,162,1752,1990,393,857,0.394089,0.458576,0.296099,Michael Adams1990,0.879017,"$825,000"
4252,Mark Aguirre,[<Position.SMALL_FORWARD: 'SMALL FORWARD'>],31,Team.DETROIT_PISTONS,78,13,2006,420,909,24,78,240,317,134,240,139,47,20,128,209,1104,1990,396,831,0.462046,0.476534,0.307692,Mark Aguirre1990,0.757098,"$1,115,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18827,Cody Zeller,[<Position.CENTER: 'CENTER'>],26,Team.CHARLOTTE_HORNETS,49,47,1243,190,345,6,22,111,141,110,223,102,38,41,62,164,497,2018,184,323,0.550725,0.569659,0.272727,Cody Zeller2018,0.787234,"$13,528,090"
18828,Tyler Zeller,[<Position.CENTER: 'CENTER'>],29,Team.ATLANTA_HAWKS,2,0,11,0,2,0,1,0,0,2,4,1,0,0,0,4,0,2018,0,1,0.000000,0.000000,0.000000,Tyler Zeller2018,NaN,"$213,948"
18829,Tyler Zeller,[<Position.CENTER: 'CENTER'>],29,Team.MEMPHIS_GRIZZLIES,4,1,82,16,28,0,0,14,18,9,9,3,1,3,4,16,46,2018,16,28,0.571429,0.571429,NaN,Tyler Zeller2018,0.777778,"$213,948"
18831,Ivica Zubac,[<Position.CENTER: 'CENTER'>],21,Team.LOS_ANGELES_LAKERS,33,12,516,112,193,0,0,57,66,54,108,25,4,27,33,73,281,2018,112,193,0.580311,0.580311,NaN,Ivica Zubac2018,0.863636,"$1,544,951"
18832,Ivica Zubac,[<Position.CENTER: 'CENTER'>],21,Team.LOS_ANGELES_CLIPPERS,26,25,524,100,186,0,0,44,60,61,139,38,10,24,37,64,244,2018,100,186,0.537634,0.537634,NaN,Ivica Zubac2018,0.733333,"$1,544,951"

In [43]:
stats1.to_csv('players_stats_and_salaries.csv',index=False)